Bump jline from 3.17.1 to 3.18.0 (#70)
Bumps [jline](https://github.com/jline/jline3) from 3.17.1 to 3.18.0.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/jline/jline3/blob/master/changelog.md">jline's changelog</a>.</em></p>
<blockquote>
<h2><a href="https://repo1.maven.org/maven2/org/jline/jline/3.18.0/">JLine 3.18.0</a></h2>
<ul>
<li><a href="https://github.com/jline/jline3/commit/e567eb70e5247473cb3f3725a066384046e7ba21"><code>e567eb70</code></a> Remove transitive dependency on the jline bundle</li>
<li><a href="https://github.com/jline/jline3/commit/6168d2b7167d28665a10fe836ae03facd7f4612e"><code>6168d2b7</code></a> Avoid javadoc warnings and do not generate javadoc for demos</li>
<li><a href="https://github.com/jline/jline3/commit/be78b98b995281dada3743e9e280dd703195ec47"><code>be78b98b</code></a> Upgrade to Jansi 2.1.0</li>
<li><a href="https://github.com/jline/jline3/commit/a67072745e3197b83317d9173406fcf9c7ea4dc7"><code>a6707274</code></a> Upgrade plugins to recente releases</li>
<li><a href="https://github.com/jline/jline3/commit/f4dd7a886155c409adbb44d3714fc04cc4c7f342"><code>f4dd7a88</code></a> Move javadoc generation into a separate profile (active by default)</li>
<li><a href="https://github.com/jline/jline3/commit/717fad869b01b2bb91ac9a3b91b00fd35a8bfb0f"><code>717fad86</code></a> Allow disabling the jline bundle module</li>
<li><a href="https://github.com/jline/jline3/commit/8ff1e1d35146a14b7c188c1c33d1020cb6ab0714"><code>8ff1e1d3</code></a> Support terminal palette, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/620">#620</a></li>
<li><a href="https://github.com/jline/jline3/commit/e2b6f97ed0ebceb3c909415baeba71c72f819c37"><code>e2b6f97e</code></a> Support for 24-bit colours, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/619">#619</a></li>
<li><a href="https://github.com/jline/jline3/commit/c20b13380e3c1d90e43cdc0bbcb68493da910bca"><code>c20b1338</code></a> Remove duplicate semicolon</li>
<li><a href="https://github.com/jline/jline3/commit/29d72f817a6742c7a83e84812aadca300f57d9fb"><code>29d72f81</code></a> Use style resolver to resolve completion styles, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/617">#617</a></li>
<li><a href="https://github.com/jline/jline3/commit/b07a7cf1240c37d597d59c3f91faeeeddb932cfc"><code>b07a7cf1</code></a> Fix wrong indentation</li>
<li><a href="https://github.com/jline/jline3/commit/99e130d6ff2d004d18cb8d89c2ca5151493a0e02"><code>99e130d6</code></a> Fix some tput limitations</li>
<li><a href="https://github.com/jline/jline3/commit/b77a0a8afea5a50a3cfa514e510ca214a0857900"><code>b77a0a8a</code></a> Inline completion re-sorts while tabbing when using groups, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/618">#618</a></li>
<li><a href="https://github.com/jline/jline3/commit/9d4a53b2e0132334c3e2d77de5a964442bbe40ea"><code>9d4a53b2</code></a> Bump Groovy to 3.0.7</li>
<li><a href="https://github.com/jline/jline3/commit/d185f7264f5233554d57681edce214e625583837"><code>d185f726</code></a> Add variable menu-list-max and sort candidates in menu-list</li>
<li><a href="https://github.com/jline/jline3/commit/538b7fa81bf73710ff4d596807386a7d8524ede4"><code>538b7fa8</code></a> Option group-persist: after double tab keep candidates grouped, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/613">#613</a></li>
<li><a href="https://github.com/jline/jline3/commit/329768ca9e9ea72a42a35e5232055d124f52b06d"><code>329768ca</code></a> Graal demo: fix resolved demo target path</li>
<li><a href="https://github.com/jline/jline3/commit/ec1115df688ca051fda2ca1a8e3e90d1d790978a"><code>ec1115df</code></a> Failed to build JLine Graal demo: NoClassDefFoundError, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/615">#615</a></li>
<li><a href="https://github.com/jline/jline3/commit/54218bc330b7ba9a4e77cb6cd9968d16d4f713b4"><code>54218bc3</code></a> Nanorc parser: align with GNU nano version 5</li>
<li><a href="https://github.com/jline/jline3/commit/82ca0f05501b29b99d66f27ebc8ef67e4f6bd9ec"><code>82ca0f05</code></a> Nanorc parser: replace Posix char class regexes with Java regexes</li>
<li><a href="https://github.com/jline/jline3/commit/172644f4281ff07951198129fdb62c85768b1e53"><code>172644f4</code></a>  Nano highlighter xml highlighting differs considerable from GNU nano highlight, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/614">#614</a></li>
<li><a href="https://github.com/jline/jline3/commit/30860bc5b947c53563b48ea5418de150f167acb8"><code>30860bc5</code></a> nano/less ignore quietly PatternSyntaxException when using system installed nanorc files, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/609">#609</a></li>
<li><a href="https://github.com/jline/jline3/commit/764a6a6ad46099c26630f1e60490f955fbc3c661"><code>764a6a6a</code></a> Less fails with PatternSyntaxException <a href="https://github-redirect.dependabot.com/jline/jline3/issues/609">#609</a></li>
<li><a href="https://github.com/jline/jline3/commit/b1a17cbc7d5f978c38d43d583e1e7bef05b8b670"><code>b1a17cbc</code></a> SystemHighlighter highlight command aliases as commands</li>
<li><a href="https://github.com/jline/jline3/commit/0e5d510e3c1ebc38b8bd6b9027b9388c0c21792b"><code>0e5d510e</code></a> SystemHighlighter fixed NPE</li>
<li><a href="https://github.com/jline/jline3/commit/924d8ff346e1ff2107fe0a25bc598b31c14e097e"><code>924d8ff3</code></a> Builtins Commands.less(): add configPath parameter</li>
<li><a href="https://github.com/jline/jline3/commit/a2281234359bb9ce2ef5173b1953b102391ec6da"><code>a2281234</code></a> Secondary prompt: fix padding when primary prompt has line breaks</li>
<li><a href="https://github.com/jline/jline3/commit/a47ccc801e7f48e8d85b8653b8fead6b68b67daa"><code>a47ccc80</code></a> Jline completion has logic issues with terminal and prompt widths (StringIndexOutOfBoundsException), fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/604">#604</a></li>
<li><a href="https://github.com/jline/jline3/commit/1a76723605f85f48fd06f35d51df60b11e187e7f"><code>1a767236</code></a> Document how I/O error in LineReader.readLine is reported, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/608">#608</a></li>
<li><a href="https://github.com/jline/jline3/commit/ca381eec4885fab0523a19718db1a3e0ec8cbea9"><code>ca381eec</code></a> Groovy REPL: highlight command and groovy language syntax</li>
<li><a href="https://github.com/jline/jline3/commit/bb5e85afd9009e9d3d917a19dcb0deab4b9b0922"><code>bb5e85af</code></a> Display command is incorrect when use here document, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/607">#607</a></li>
<li><a href="https://github.com/jline/jline3/commit/0ba7e8137e0ff132f05c4c176daccd149e14ec66"><code>0ba7e813</code></a> edit-and-execute widget: set BRACKETED_PASTE_OFF before editing</li>
<li><a href="https://github.com/jline/jline3/commit/23034dbfb50ea4da2322be652c4a07345f646f39"><code>23034dbf</code></a> SystemRegistryImpl: fixed IndexOutOfBoundsException</li>
<li><a href="https://github.com/jline/jline3/commit/d66e7349017098458e7961acfa314198c666ada2"><code>d66e7349</code></a> DefaultParser: fixed default variable regex</li>
<li><a href="https://github.com/jline/jline3/commit/eb3e07c88782179f3b1c185eb5b7a8efd2fc9f67"><code>eb3e07c8</code></a> SystemRegistryImpl: method consoleEngine() is now public</li>
<li><a href="https://github.com/jline/jline3/commit/6580789cd5eca02317007afe522c8f41060bbc45"><code>6580789c</code></a> Keep argument sorting in large argument list when formatting candidates for terminal into multiple columns</li>
<li><a href="https://github.com/jline/jline3/commit/d92701d4b41cee07cd2110d1e0b20ab2982021d6"><code>d92701d4</code></a> Auto suggestion error when type &quot;\&quot; character, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/602">#602</a></li>
<li><a href="https://github.com/jline/jline3/commit/495b534afb1e0c7dbfb7780869a424c62d44fd7b"><code>495b534a</code></a> ConsoleEngineImpl: exclude pipe name aliases from command completion</li>
<li><a href="https://github.com/jline/jline3/commit/df99187246f4021f4fe12a64f52cca9d55aeb809"><code>df991872</code></a> Show auto-suggestions when the reader starts reading, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/598">#598</a></li>
<li><a href="https://github.com/jline/jline3/commit/ea6dd89cdc98abdfc77c262444fca91da3c1080d"><code>ea6dd89c</code></a> Autosuggestion choices are not refreshed after tab, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/545">#545</a></li>
<li><a href="https://github.com/jline/jline3/commit/2e6638cb6d4f27bc61bbb6ca6059e5df0384e2d0"><code>2e6638cb</code></a> Widgets: added widget name public constants</li>
<li><a href="https://github.com/jline/jline3/commit/a015a5dfd66262ab463f24e2b25aec03c5fa2982"><code>a015a5df</code></a> JLine option AUTO_MENU_LIST: bug fix for candidate list start position calculation</li>
<li><a href="https://github.com/jline/jline3/commit/a5686ab138225ee8214c68bda8c33fbaf2af5d26"><code>a5686ab1</code></a> JLine option AUTO_MENU_LIST: candidate list is wrongly positioned, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/600">#600</a></li>
<li><a href="https://github.com/jline/jline3/commit/ea8d0d3b87a6dd74876fc67f909c3b769433294f"><code>ea8d0d3b</code></a> SystemRegistryImpl: refactoring command output redirection</li>
<li><a href="https://github.com/jline/jline3/commit/40c4d3241fc242525cf7050ec0b977494620065d"><code>40c4d324</code></a> Add completion candidate suffix test, <a href="https://github-redirect.dependabot.com/jline/jline3/issues/425">#425</a></li>
<li><a href="https://github.com/jline/jline3/commit/404565b2ede2b9b83fab2c350b2806126a11e33f"><code>404565b2</code></a> Dumb terminal when piping input to console app disallows ANSI formatting, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/299">#299</a></li>
<li><a href="https://github.com/jline/jline3/commit/fe1f27179461fdecc88f2cf01de812784bddfad9"><code>fe1f2717</code></a> Windows gitbash: JLine will create dumb terminal if JNA lib is in classpath, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/599">#599</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/jline/jline3/commit/78734a7de0465ed341962a9cf4866287b22da2ca"><code>78734a7</code></a> [maven-release-plugin] prepare release jline-parent-3.18.0</li>
<li><a href="https://github.com/jline/jline3/commit/e567eb70e5247473cb3f3725a066384046e7ba21"><code>e567eb7</code></a> Remove transitive dependency on the jline bundle</li>
<li><a href="https://github.com/jline/jline3/commit/6168d2b7167d28665a10fe836ae03facd7f4612e"><code>6168d2b</code></a> Avoid javadoc warnings and do not generate javadoc for demos</li>
<li><a href="https://github.com/jline/jline3/commit/be78b98b995281dada3743e9e280dd703195ec47"><code>be78b98</code></a> Upgrade to Jansi 2.1.0</li>
<li><a href="https://github.com/jline/jline3/commit/a67072745e3197b83317d9173406fcf9c7ea4dc7"><code>a670727</code></a> Upgrade plugins to recente releases</li>
<li><a href="https://github.com/jline/jline3/commit/f4dd7a886155c409adbb44d3714fc04cc4c7f342"><code>f4dd7a8</code></a> Move javadoc generation into a separate profile (active by default)</li>
<li><a href="https://github.com/jline/jline3/commit/717fad869b01b2bb91ac9a3b91b00fd35a8bfb0f"><code>717fad8</code></a> Allow disabling the jline bundle module</li>
<li><a href="https://github.com/jline/jline3/commit/8ff1e1d35146a14b7c188c1c33d1020cb6ab0714"><code>8ff1e1d</code></a> Support terminal palette, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/620">#620</a></li>
<li><a href="https://github.com/jline/jline3/commit/e2b6f97ed0ebceb3c909415baeba71c72f819c37"><code>e2b6f97</code></a> Support for 24-bit colours, fixes <a href="https://github-redirect.dependabot.com/jline/jline3/issues/619">#619</a></li>
<li><a href="https://github.com/jline/jline3/commit/c20b13380e3c1d90e43cdc0bbcb68493da910bca"><code>c20b133</code></a> Remove duplicate semicolon</li>
<li>Additional commits viewable in <a href="https://github.com/jline/jline3/compare/jline-parent-3.17.1...jline-parent-3.18.0">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://api.dependabot.com/badges/compatibility_score?dependency-name=org.jline:jline&package-manager=maven&previous-version=3.17.1&new-version=3.18.0)](https://dependabot.com/compatibility-score/?dependency-name=org.jline:jline&package-manager=maven&previous-version=3.17.1&new-version=3.18.0)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
If all status checks pass Dependabot will automatically merge this pull request.

[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language
- `@dependabot badge me` will comment on this PR with code to add a "Dependabot enabled" badge to your readme

Additionally, you can set the following in your Dependabot [dashboard](https://app.dependabot.com):
- Update frequency (including time of day and day of week)
- Pull request limits (per update run and/or open at any time)
- Automerge options (never/patch/minor, and dev/runtime dependencies)
- Out-of-range updates (receive only lockfile updates, if desired)
- Security updates (receive only security updates, if desired)



</details>